FROM node:23.5.0 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx:1.27.3-alpine AS production

COPY --from=build /app/build /usr/share/nginx/html

# Since containers should only run one process, daemon is set to off so that
# nginx runs in the foreground rather than the background.
CMD [ "nginx", "-g", "daemon off;"]