FROM python:3.9.21

WORKDIR /flask-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000

CMD [ "waitress-serve", "--port=5000", "--call", "server:create_app"]